import { CONFIG_KEYS, ConfigGroup, ConfigValueType, SmsProvider } from '@app/contracts';
import type { ConfigDefault } from './config-defaults';

/** 短信模块默认配置，按原有顺序汇入平台默认配置清单。 */
export const SMS_DEFAULT_CONFIGS: ConfigDefault[] = [
  {
    key: CONFIG_KEYS.sms.provider,
    value: SmsProvider.Log,
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '短信服务商：aliyun / tencent / volcano / log（默认 log，仅打日志不真正发送）',
  },
  {
    key: CONFIG_KEYS.sms.codeLength,
    value: '6',
    type: ConfigValueType.Number,
    group: ConfigGroup.Sms,
    remark: '验证码位数',
  },
  {
    key: CONFIG_KEYS.sms.codeTtl,
    value: '300',
    type: ConfigValueType.Number,
    group: ConfigGroup.Sms,
    remark: '验证码有效期（秒）',
  },
  {
    key: CONFIG_KEYS.sms.sendInterval,
    value: '60',
    type: ConfigValueType.Number,
    group: ConfigGroup.Sms,
    remark: '同一手机号两次发送的最小间隔（秒）',
  },
  {
    key: CONFIG_KEYS.sms.countryCode,
    value: '+86',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '国际区号（E.164），腾讯云等需带区号的服务商使用',
  },
  {
    key: CONFIG_KEYS.sms.aliyunAccessKeyId,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '阿里云短信 AccessKeyId',
    secret: true,
  },
  {
    key: CONFIG_KEYS.sms.aliyunAccessKeySecret,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '阿里云短信 AccessKeySecret',
    secret: true,
  },
  {
    key: CONFIG_KEYS.sms.aliyunSignName,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '阿里云短信签名',
  },
  {
    key: CONFIG_KEYS.sms.aliyunTemplateCode,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '阿里云短信模板 Code（模板变量需用 ${code}）',
  },
  {
    key: CONFIG_KEYS.sms.aliyunEndpoint,
    value: 'dysmsapi.aliyuncs.com',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '阿里云短信服务 Endpoint',
  },
  {
    key: CONFIG_KEYS.sms.tencentSecretId,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '腾讯云 SecretId',
    secret: true,
  },
  {
    key: CONFIG_KEYS.sms.tencentSecretKey,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '腾讯云 SecretKey',
    secret: true,
  },
  {
    key: CONFIG_KEYS.sms.tencentSdkAppId,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '腾讯云短信应用 SdkAppId',
  },
  {
    key: CONFIG_KEYS.sms.tencentSignName,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '腾讯云短信签名',
  },
  {
    key: CONFIG_KEYS.sms.tencentTemplateId,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '腾讯云短信模板 ID（模板变量按顺序，第一个为验证码）',
  },
  {
    key: CONFIG_KEYS.sms.tencentRegion,
    value: 'ap-guangzhou',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '腾讯云短信地域',
  },
  {
    key: CONFIG_KEYS.sms.volcanoAccessKeyId,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '火山引擎 AccessKeyId',
    secret: true,
  },
  {
    key: CONFIG_KEYS.sms.volcanoSecretAccessKey,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '火山引擎 SecretAccessKey',
    secret: true,
  },
  {
    key: CONFIG_KEYS.sms.volcanoSmsAccount,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '火山引擎短信账号（SmsAccount）',
  },
  {
    key: CONFIG_KEYS.sms.volcanoSignName,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '火山引擎短信签名',
  },
  {
    key: CONFIG_KEYS.sms.volcanoTemplateId,
    value: '',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '火山引擎短信模板 ID（模板变量需用 ${code}）',
  },
  {
    key: CONFIG_KEYS.sms.volcanoRegion,
    value: 'cn-north-1',
    type: ConfigValueType.String,
    group: ConfigGroup.Sms,
    remark: '火山引擎地域',
  },
];
